

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
 

    - name: Bump version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        snapshot: "false"

    - name: Print Version
      run: "echo 'New Version: ${{steps.bump.outputs.version}}'"


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push project to docker hub
      if: steps.bump.outputs.bumped == false
      uses: docker/build-push-action@v6
      with:
        context: "./dockerfile"
        push: true
        tags: infinityam1/first_repo:${{steps.bump.outputs.version}}	 
